language: go

go:
  - "1.10"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - cd cmd/go-scribe && go build
  - cd cmd/client && go build

after_success:
  - bash <(curl -s https://codecov.io/bash)
