FROM alpine:latest

LABEL Romanos Trechlis "r.trechlis@gmail.com"

COPY logStreamer /usr/local/bin/logStreamer

WORKDIR /logs

ENTRYPOINT ["logStreamer -path ./ -pprof"]

ENV SERVER_PORT 8080
ENV PPROF_PORT 1111
EXPOSE $SERVER_PORT $PPROF_PORT
