// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logScribe.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	logScribe.proto

It has these top-level messages:
	LogRequest
	LogResponse
	PingRequest
	PingResponse
	RegisterRequest
	RegisterResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// message is the structure that get serialized
// the numbered fields are necessary for the serialization.
// LogRequest is the structure that gets serialized
// and then sent to rpc server.
type LogRequest struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Path     string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Line     string `protobuf:"bytes,3,opt,name=line" json:"line,omitempty"`
}

func (m *LogRequest) Reset()                    { *m = LogRequest{} }
func (m *LogRequest) String() string            { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()               {}
func (*LogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *LogRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *LogRequest) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

// LogResponse is the reply from rpc server
type LogResponse struct {
	Res string `protobuf:"bytes,1,opt,name=res" json:"res,omitempty"`
}

func (m *LogResponse) Reset()                    { *m = LogResponse{} }
func (m *LogResponse) String() string            { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()               {}
func (*LogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogResponse) GetRes() string {
	if m != nil {
		return m.Res
	}
	return ""
}

// PingRequest sends two numbers to mediator
type PingRequest struct {
	A          int32  `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B          int32  `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
	StreamerId string `protobuf:"bytes,3,opt,name=streamerId" json:"streamerId,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PingRequest) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *PingRequest) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *PingRequest) GetStreamerId() string {
	if m != nil {
		return m.StreamerId
	}
	return ""
}

// PingResponse returns the mediator's response
type PingResponse struct {
	Res int32 `protobuf:"varint,2,opt,name=res" json:"res,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PingResponse) GetRes() int32 {
	if m != nil {
		return m.Res
	}
	return 0
}

type RegisterRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RegisterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type RegisterResponse struct {
	Res string `protobuf:"bytes,1,opt,name=res" json:"res,omitempty"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RegisterResponse) GetRes() string {
	if m != nil {
		return m.Res
	}
	return ""
}

func init() {
	proto.RegisterType((*LogRequest)(nil), "com.romanostrechlis.scribe.api.LogRequest")
	proto.RegisterType((*LogResponse)(nil), "com.romanostrechlis.scribe.api.LogResponse")
	proto.RegisterType((*PingRequest)(nil), "com.romanostrechlis.scribe.api.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "com.romanostrechlis.scribe.api.PingResponse")
	proto.RegisterType((*RegisterRequest)(nil), "com.romanostrechlis.scribe.api.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "com.romanostrechlis.scribe.api.RegisterResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LogScribe service

type LogScribeClient interface {
	// the LogScribe service sends a LogRequest
	// and recieves a LogResponse
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
}

type logScribeClient struct {
	cc *grpc.ClientConn
}

func NewLogScribeClient(cc *grpc.ClientConn) LogScribeClient {
	return &logScribeClient{cc}
}

func (c *logScribeClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := grpc.Invoke(ctx, "/com.romanostrechlis.scribe.api.LogScribe/Log", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LogScribe service

type LogScribeServer interface {
	// the LogScribe service sends a LogRequest
	// and recieves a LogResponse
	Log(context.Context, *LogRequest) (*LogResponse, error)
}

func RegisterLogScribeServer(s *grpc.Server, srv LogScribeServer) {
	s.RegisterService(&_LogScribe_serviceDesc, srv)
}

func _LogScribe_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogScribeServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.romanostrechlis.scribe.api.LogScribe/Log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogScribeServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogScribe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.romanostrechlis.scribe.api.LogScribe",
	HandlerType: (*LogScribeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _LogScribe_Log_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logScribe.proto",
}

// Client API for Pinger service

type PingerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type pingerClient struct {
	cc *grpc.ClientConn
}

func NewPingerClient(cc *grpc.ClientConn) PingerClient {
	return &pingerClient{cc}
}

func (c *pingerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/com.romanostrechlis.scribe.api.Pinger/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pinger service

type PingerServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterPingerServer(s *grpc.Server, srv PingerServer) {
	s.RegisterService(&_Pinger_serviceDesc, srv)
}

func _Pinger_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.romanostrechlis.scribe.api.Pinger/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pinger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.romanostrechlis.scribe.api.Pinger",
	HandlerType: (*PingerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Pinger_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logScribe.proto",
}

// Client API for Register service

type RegisterClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type registerClient struct {
	cc *grpc.ClientConn
}

func NewRegisterClient(cc *grpc.ClientConn) RegisterClient {
	return &registerClient{cc}
}

func (c *registerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := grpc.Invoke(ctx, "/com.romanostrechlis.scribe.api.Register/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Register service

type RegisterServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

func RegisterRegisterServer(s *grpc.Server, srv RegisterServer) {
	s.RegisterService(&_Register_serviceDesc, srv)
}

func _Register_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.romanostrechlis.scribe.api.Register/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Register_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.romanostrechlis.scribe.api.Register",
	HandlerType: (*RegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Register_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logScribe.proto",
}

func init() { proto.RegisterFile("logScribe.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4f, 0xb3, 0x40,
	0x10, 0xc6, 0x5f, 0x4a, 0xdb, 0xb4, 0xd3, 0xe6, 0x6d, 0xb3, 0x27, 0xc2, 0xa1, 0x36, 0x1b, 0x0f,
	0x46, 0x0d, 0x9a, 0x1a, 0xbf, 0x80, 0xb7, 0x26, 0x1c, 0x1a, 0xbc, 0x79, 0x72, 0x81, 0x91, 0x6e,
	0xc2, 0xb2, 0xb8, 0x8b, 0x27, 0xbf, 0xbc, 0xd9, 0xe5, 0x4f, 0xd1, 0x44, 0xcb, 0xed, 0xd9, 0x61,
	0xe6, 0xf9, 0xcd, 0x3c, 0x01, 0x56, 0xb9, 0xcc, 0x9e, 0x13, 0xc5, 0x63, 0x0c, 0x4a, 0x25, 0x2b,
	0x49, 0x36, 0x89, 0x14, 0x81, 0x92, 0x82, 0x15, 0x52, 0x57, 0x0a, 0x93, 0x63, 0xce, 0x75, 0xa0,
	0xeb, 0x0e, 0x56, 0x72, 0x7a, 0x00, 0x08, 0x65, 0x16, 0xe1, 0xfb, 0x07, 0xea, 0x8a, 0xf8, 0x30,
	0x7b, 0xe3, 0x39, 0x16, 0x4c, 0xa0, 0xe7, 0x6c, 0x9d, 0xab, 0x79, 0xd4, 0xbd, 0x09, 0x81, 0x71,
	0xc9, 0xaa, 0xa3, 0x37, 0xb2, 0x75, 0xab, 0x4d, 0x2d, 0xe7, 0x05, 0x7a, 0x6e, 0x5d, 0x33, 0x9a,
	0x5e, 0xc0, 0xc2, 0x3a, 0xea, 0x52, 0x16, 0x1a, 0xc9, 0x1a, 0x5c, 0x85, 0xba, 0x71, 0x33, 0x92,
	0xee, 0x61, 0x71, 0xe0, 0x45, 0xc7, 0x5c, 0x82, 0xc3, 0xec, 0xe7, 0x49, 0xe4, 0x30, 0xf3, 0x8a,
	0x2d, 0x62, 0x12, 0x39, 0x31, 0xd9, 0x00, 0x98, 0xad, 0x99, 0x40, 0xb5, 0x4f, 0x1b, 0x4a, 0xaf,
	0x42, 0xb7, 0xb0, 0xac, 0xad, 0xbe, 0xc3, 0xea, 0x79, 0x0b, 0x7b, 0x84, 0x55, 0x84, 0x19, 0xd7,
	0x15, 0xaa, 0x16, 0xf8, 0x1f, 0x46, 0x3c, 0x6d, 0x16, 0x1a, 0xf1, 0xd4, 0x1c, 0xc1, 0xd2, 0x54,
	0xb5, 0x87, 0x19, 0x4d, 0x2f, 0x61, 0x7d, 0x1a, 0xfb, 0xed, 0x92, 0x9d, 0x80, 0x79, 0xd8, 0xe6,
	0x4d, 0x5e, 0xc1, 0x0d, 0x65, 0x46, 0xae, 0x83, 0xbf, 0x13, 0x0f, 0x4e, 0x71, 0xfb, 0x37, 0x83,
	0x7a, 0x6b, 0x3c, 0xfd, 0xb7, 0x13, 0x30, 0x35, 0xd7, 0xa2, 0x22, 0x09, 0x8c, 0x8d, 0x22, 0x67,
	0x0d, 0x7a, 0x41, 0xfb, 0xb7, 0xc3, 0x9a, 0x3b, 0xdc, 0x27, 0xcc, 0xda, 0x0c, 0x88, 0xec, 0xe9,
	0xbb, 0x73, 0x3e, 0x3f, 0x02, 0xf7, 0xef, 0x87, 0x0f, 0xb4, 0xf0, 0xa7, 0xc9, 0x8b, 0xcb, 0x4a,
	0x1e, 0x4f, 0xed, 0x5f, 0xfc, 0xf0, 0x15, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x74, 0x0d, 0x5e, 0xd8,
	0x02, 0x00, 0x00,
}
